app = "whatsapputility"

primary_region = "bom"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"

[[mounts]]
  source = "whatsapp_data"
  destination = "/data"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
